# Generated by Django 5.2.12 on 2026-04-24 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Routes', '0003_alter_route_id_alter_station_city_alter_station_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=64)),
                ('last', models.CharField(max_length=64)),
                ('routes', models.ManyToManyField(blank=True, related_name='passengers', to='Routes.route')),
            ],
        ),
    ]
