# Generated by Django 5.2.12 on 2026-04-24 23:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Routes', '0004_passenger'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='passengers',
            field=models.ManyToManyField(blank=True, related_name='routes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='passenger',
        ),
    ]
